### ISSUE TITLE
assert not unfinished, unfinished error

### ISSUE THREAD

**Issue by peterdfields** [uio-bmi/graph_peak_caller#13]
Hi,

I'm trying to run graph_peak_caller on a ATAC-seq data which is aligned to a single test chromosome graph which was generated with the PGGB pipeline. After aligning the raw data to the graph using `vg map`, when I try to run `graph_peak_caller callpeaks -g ch19.nobg -s alignments.json`, I see the following:

```
DEBUG:matplotlib:$HOME=/home/fieldp
DEBUG:matplotlib:CONFIGDIR=/home/fieldp/.config/matplotlib
DEBUG:matplotlib:matplotlib data path: /home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:loaded rc file /home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc
DEBUG:matplotlib:matplotlib version 3.0.0
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: ['scipy.ndimage._ni_label', 'graph_peak_caller.logging_config', 'scipy.integrate._quad_vec', '_stat', 'builtins', 'graph_peak_caller.multiplegraphscallpeaks', 'ctypes._endian', 'concurrent.futures._base', 'scipy.version', 'email', 'asyncio.base_events', 'json', 'types', 'numpy.lib.arrayterator', 'numpy.core.getlimits', 'typing.re', 'zlib', 'scipy.sparse.linalg.eigen.lobpcg', 'scipy.optimize._spectral', 'Bio.SeqIO.PirIO', 'scipy.optimize._differentialevolution', 'scipy.integrate._quadpack', 'scipy.sparse.linalg.eigen.arpack._arpack', 'scipy.sparse.csc', 'ctypes', 'graph_peak_caller.peakcollection', 'scipy.linalg.linalg_version', 'scipy.linalg.cython_blas', 'scipy.linalg._fblas', 'scipy.sparse.extract', '_compression', 'matplotlib.cbook.deprecation', '_codecs', 'numpy.matrixlib', 'numpy.random._common', 'asyncio.streams', 'heapq', 'graph_peak_caller.linear_filter', 'inspect', 'scipy.integrate.quadrature', 'scipy.spatial.qhull', 'google.protobuf.internal.encoder', 'pyparsing', 'async_generator._util', 'matplotlib._color_data', 'scipy.linalg._procrustes', 'graph_peak_caller.control.linearintervals', 'numpy.lib.stride_tricks', '_frozen_importlib', 'scipy.interpolate._bsplines', 'google.protobuf.internal.enum_type_wrapper', 'scipy.fft._pocketfft.helper', 'signal', '_warnings', 'stream.release', 'graph_peak_caller.shiftestimation', 'graph_peak_caller.reporter', 'offsetbasedgraph.indexedinterval', 'graph_peak_caller.custom_exceptions', 'offsetbasedgraph.vcfmap', 'numpy.core._dtype', 'numpy.core.shape_base', 'scipy.sparse.csr', 'scipy.linalg._solve_toeplitz', 'numpy.lib.function_base', 'six.moves', 'sre_compile', 'scipy.fft._helper', 'scipy.optimize._lsq.bvls', 'numpy.version', 'xml.sax.saxutils', 'Bio.GenBank.Scanner', '_elementtree', 'numpy.random._bounded_integers', 'scipy.integrate._ode', 'scipy.optimize.slsqp', 'google.protobuf.descriptor_pb2', 'struct', 'xml.dom.minidom', 'xml.sax._exceptions', 'scipy.special._logsumexp', 'numpy.lib.npyio', 'google.protobuf.internal', '_multiprocessing', 'scipy.optimize._lsq.dogbox', 'scipy.sparse.linalg.eigen.lobpcg.lobpcg', 'scipy.optimize._differentiable_functions', 'unittest.suite', 'warnings', 'numpy.random._pickle', 'xml.etree.cElementTree', 'functools', 'pyexpat.errors', 'urllib.response', 'scipy.optimize.nonlin', 'scipy.interpolate', 'mpl_toolkits', 'scipy.special._ellip_harm_2', 'posixpath', 'google.protobuf.internal.python_message', 'asyncio.log', 'numpy.linalg.lapack_lite', 'numpy.polynomial.hermite', 'scipy.spatial._voronoi', 'scipy.spatial.distance', '_random', 'scipy.integrate._ivp.ivp', 'scipy.interpolate.rbf', 'scipy.interpolate._cubic', 'numpy.ma', 'scipy.optimize.linesearch', 'asyncio.tasks', 'typing.io', '_functools', 'numpy.random._mt19937', 'asyncio.subprocess', 'scipy.fft', 'scipy.sparse.linalg.eigen', 'async_generator', 'scipy.integrate._ivp.lsoda', 'email.feedparser', 'scipy.optimize.zeros', '_hashlib', 'xml.etree.ElementPath', 'scipy.ndimage.measurements', 'scipy.spatial._hausdorff', 'scipy.spatial._plotutils', 'stat', '_cython_0_29_19', 'numpy.polynomial.chebyshev', 'pwd', 'graph_peak_caller.callpeaks', 'scipy.linalg._decomp_polar', 'offsetbasedgraph', 'scipy.optimize._minimize', 'shutil', '_posixsubprocess', 'numpy.core.records', 'scipy.spatial.transform.rotation', 'scipy.sparse.linalg.isolve', 'numpy.core._methods', 'scipy.sparse.bsr', 'scipy.optimize._remove_redundancy', 'numpy.core.numerictypes', 'email.encoders', 'ntpath', 'scipy._lib._uarray._backend', 'scipy.sparse.linalg.interface', 'Bio.SeqIO.IgIO', 'scipy.optimize._trlib', '_ni_label', 'token', 'graph_peak_caller.postprocess', 'scipy.optimize._linprog_util', 'numpy.random._generator', 'xml.dom.xmlbuilder', 'scipy._lib.messagestream', 'email._parseaddr', '_collections_abc', 'scipy.sparse.csgraph._matching', 'scipy.optimize._shgo', 'scipy.integrate._ivp.dop853_coefficients', 'google.protobuf.internal.decoder', 'numpy.lib.shape_base', 'google.protobuf.descriptor', 'scipy._lib.doccer', 'numpy.testing._private.utils', '_bz2', 'scipy.spatial._spherical_voronoi', 'scipy.special._ufuncs_cxx', 'numpy.polynomial.polyutils', 'pyvg.conversion', 'Bio.SeqIO.GckIO', 'stream', 'email.iterators', 'scipy.optimize._trustregion_constr.canonical_constraint', 're', 'scipy.sparse.linalg.isolve.lgmres', 'asyncio.protocols', '_weakrefset', 'scipy.constants', 'numpy.core._add_newdocs', 'scipy.optimize._trustregion_constr.qp_subproblem', 'numpy._pytesttester', 'scipy.special.orthogonal', 'scipy._lib._threadsafety', 'scipy.optimize.optimize', 'Bio.SeqIO.SnapGeneIO', 'xml.dom.domreg', 'scipy.integrate._ivp.common', 'scipy.fft._pocketfft.realtransforms', 'scipy.optimize._trustregion_constr', 'numpy.core.memmap', 'scipy.optimize._lsq.trf', '_bisect', 'scipy._lib.uarray', 'scipy.stats._distn_infrastructure', 'http.client', 'sre_parse', 'scipy.integrate._bvp', 'cycler', 'scipy.sparse.csgraph._flow', 'encodings.latin_1', 'scipy.optimize._linprog', 'scipy.interpolate._bspl', 'scipy._distributor_init', '_cython_0_29_13', 'numpy.linalg._umath_linalg', 'scipy.optimize.moduleTNC', 'scipy.linalg.lapack', 'numpy.core._asarray', 'gettext', '_compat_pickle', 'scipy.optimize._linprog_simplex', 'select', 'scipy.sparse._csparsetools', 'socket', 'scipy.optimize.lbfgsb', 'scipy.stats._binned_statistic', 'google.protobuf.internal.containers', 'numpy.core.fromnumeric', 'scipy.integrate._ivp', 'numpy.core.arrayprint', 'matplotlib._version', 'Bio.SeqIO', 'importlib.machinery', 'scipy.linalg.decomp_schur', 'scipy.optimize._lsap_module', 'scipy.sparse.linalg.isolve._iterative', 'urllib.request', 'numpy.lib.nanfunctions', 'scipy.sparse.csgraph._traversal', 'scipy.optimize._linprog_ip', 'encodings.unicode_escape', 'scipy.misc.common', 'Bio.SeqIO.SeqXmlIO', 'scipy.integrate.quadpack', 'scipy.linalg._sketches', 'email.message', 'asyncio.futures', 'pyvg.util', 'graph_peak_caller.intervals', 'importlib.abc', 'asyncio.coroutines', 'offsetbasedgraph.multipathinterval', 'scipy.optimize._numdiff', '_datetime', 'xml.dom.NodeFilter', 'json.scanner', 'numpy.fft._pocketfft', '_io', 'scipy.fft._pocketfft', 'Bio.SwissProt', 'graph_peak_caller.postprocess.graphs', 'encodings.utf_8', 'numpy.ctypeslib', 'scipy.optimize._cobyla', 'numpy.core._dtype_ctypes', 'scipy.optimize._trustregion_constr.tr_interior_point', 'numpy.lib.format', 'scipy.interpolate.fitpack', 'Bio.Align._aligners', '_heapq', 'scipy._lib._version', 'Bio.SeqIO.SffIO', 'offsetbasedgraph.regionpath', 'quopri', 'numpy.lib.scimath', '_signal', 'difflib', 'atexit', 'enum', 'Bio', 'scipy.sparse.linalg.isolve.iterative', 'google.protobuf.internal.wire_format', 'scipy.optimize._nnls', 'numpy.lib.utils', 'json.encoder', 'email.utils', 'xml.sax.handler', 'base64', 'Bio.GenBank', 'Bio.Sequencing.Phd', 'scipy.special.specfun', 'graph_peak_caller.analysis', 'scipy.spatial.transform', 'scipy.linalg.misc', 'scipy.spatial.transform._rotation_groups', 'fnmatch', 'graph_peak_caller.util', 'scipy.sparse.linalg.eigen.arpack', 'numpy', 'Bio.Alphabet.IUPAC', 'Bio.SeqIO.AceIO', 'scipy.integrate.lsoda', 'graph_peak_caller.eventsorter', 'numpy.lib.arraypad', 'scipy.special._ellip_harm', 'Bio.SeqIO.TabIO', 'numpy.lib.histograms', 'scipy.ndimage.fourier', 'scipy.sparse.csgraph._shortest_path', 'scipy.sparse.linalg.isolve.lsqr', 'scipy.optimize.minpack2', 'Bio.SeqIO.PhdIO', 'selectors', 'scipy.stats.mstats', 'offsetbasedgraph.graph', 'scipy.spatial._procrustes', 'scipy.sparse.csgraph._laplacian', 'scipy.sparse.linalg._norm', 'scipy.constants.constants', 'gzip', 'scipy.optimize._shgo_lib.sobol_seq', 'numpy.fft.helper', 'scipy._lib._testutils', 'scipy.optimize.tnc', 'scipy.linalg.flinalg', 'numpy.random._bit_generator', 'scipy.sparse.csgraph', 'email.parser', 'offsetbasedgraph.graphwithreversals', 'scipy._lib.decorator', 'scipy.sparse.linalg', 'collections.abc', 'scipy.sparse._matrix_io', 'scipy.stats._distr_params', 'numpy.core.einsumfunc', 'asyncio.locks', 'scipy.optimize._linprog_rs', 'scipy.special.spfun_stats', 'concurrent.futures', 'graph_peak_caller.postprocess.subgraphanalyzer', 'numpy.random', 'graph_peak_caller.command_line_interface', 'numpy.ma.extras', 'pyexpat', 'numpy.random._sfc64', 'numpy.fft', 'scipy.fft._basic', 'scipy.optimize._hessian_update_strategy', 'scipy.optimize._trustregion_exact', 'encodings.aliases', 'traceback', 'numpy.polynomial.laguerre', 'scipy.stats.statlib', 'numpy._distributor_init', 'unittest.runner', 'multiprocessing.context', 'scipy.sparse.linalg.isolve.minres', 'tokenize', 'codecs', 'scipy.optimize._trustregion_constr.projections', 'importlib._bootstrap', 'os', 'sysconfig', 'numpy.lib._version', 'scipy._lib._numpy_compat', 'scipy.optimize._root_scalar', 'Bio.SeqIO.Interfaces', 'weakref', 'scipy.sparse.dia', 'array', 'scipy.interpolate.interpnd', 'scipy._lib.deprecation', 'errno', 'scipy.optimize._zeros', 'email.base64mime', 'scipy.sparse.linalg._expm_multiply', 'scipy.ndimage.morphology', 'numpy.core._multiarray_umath', 'graph_peak_caller.analysis.nongraphpeaks', 'json.decoder', 'encodings.raw_unicode_escape', 'scipy.linalg._solvers', 'scipy.optimize._group_columns', 'http', 'numpy.lib.ufunclike', '_locale', 'scipy.sparse.coo', 'scipy.sparse.construct', 'unittest.util', 'scipy.interpolate._fitpack_impl', 'numpy.dual', '_bootlocale', 'uu', 'scipy.optimize.cobyla', 'urllib.error', 'scipy.optimize._lsq.least_squares', 'numpy.linalg.linalg', 'graph_peak_caller.mindense', 'graph_peak_caller.sample.sparsegraphpileup', 'graph_peak_caller', 'contextlib', 'Bio._py3k', 'pyvg.vgobjects', 'scipy.stats.stats', 'asyncio.sslproto', 'google.protobuf.reflection', 'google.protobuf.internal.well_known_types', 'scipy.interpolate.fitpack2', 'scipy.stats.mstats_basic', 'Bio.File', 'graph_peak_caller.postprocess.indel_scores', '_ast', 'google.protobuf.text_encoding', 'Bio.SeqIO.PdbIO', 'unittest.loader', 'Bio.Data.SCOPData', 'scipy.optimize._trustregion', 'numpy.compat', 'scipy.optimize._lsq.trf_linear', '_operator', 'scipy.sparse.linalg.isolve._gcrotmk', 'scipy.sparse.csgraph._tools', 'xml.etree.ElementTree', 'numpy.core._ufunc_config', 'Bio.SeqIO.UniprotIO', 'concurrent.futures.thread', 'opcode', 'scipy.sparse', 'numpy.testing._private.nosetester', '_lzma', '_sre', '_socket', 'scipy.integrate._dop', 'scipy.optimize._trustregion_constr.report', 'calendar', 'scipy.fft._pocketfft.pypocketfft', 'graph_peak_caller.postprocess.holecleaner', 'numpy.core._internal', 'scipy.optimize._lsq.common', 'pyvg.alignmentcollection', 'google', 'google.protobuf.descriptor_database', 'xml.dom', 'scipy.optimize._trlib._trlib', 'scipy.linalg.decomp_cholesky', 'sqlite3', 'graph_peak_caller.control', 'scipy.sparse.csgraph._reordering', 'Bio.SeqIO.XdnaIO', 'scipy.linalg', 'scipy.optimize._lsq.givens_elimination', 'google.protobuf', 'scipy.optimize.minpack', 'scipy.optimize.nnls', 'numpy.core.function_base', 'google.protobuf.message_factory', 'numpy.core._type_aliases', '_weakref', 'urllib.parse', 'scipy.integrate._ivp.radau', 'numpy.testing._private.decorators', '_ctypes', 'concurrent.futures.process', 'scipy.integrate._odepack', 'scipy.spatial.ckdtree', 'asyncio.selector_events', 'xml.dom.minicompat', 'offsetbasedgraph.sequencegraph', 'graph_peak_caller.shiftestimation.shift_estimation_multigraph', '__future__', 'Bio.SeqIO.NibIO', 'site', 'scipy.stats.contingency', 'scipy.ndimage._ni_docstrings', 'email.errors', 'scipy.spatial.transform._rotation_spline', 'Bio.SeqRecord', 'scipy._lib', 'Bio.SeqFeature', 'itertools', 'numpy.lib', 'scipy.optimize', 'Bio.SeqIO.InsdcIO', 'scipy.sparse.base', 'scipy.optimize._lsq.lsq_linear', 'argparse', 'numpy.polynomial.hermite_e', 'asyncio.events', 'posix', 'scipy.sparse.sputils', 'scipy.interpolate._fitpack', '_string', 'matplotlib.rcsetup', 'scipy.optimize._trustregion_krylov', 'dis', 'scipy.stats.mvn', 'pyvg', 'scipy.interpolate.polyint', 'scipy.sparse.linalg.isolve.utils', 'google.protobuf.descriptor_pool', 'Bio.SeqIO.SwissIO', 'scipy.stats._multivariate', 'email.charset', 'numpy.core.umath', 'numpy.lib.index_tricks', 'scipy.fft._backend', 'scipy._lib._util', 'Bio.SeqIO.QualityIO', 'numpy.compat._inspect', 'scipy.stats._discrete_distns', 'Bio.Data', 'numpy.core.overrides', 'scipy.ndimage._ni_support', 'email._encoded_words', '_json', 'cython_runtime', 'ssl', 'logging', 'ipaddress', 'scipy.linalg.basic', 'pprint', 'scipy.optimize._lbfgsb', 'scipy._lib.six', 'grp', 'Bio.Sequencing', 'Bio.Data.CodonTable', 'scipy.sparse.csgraph._validation', 'graph_peak_caller.sparsepvalues', 'scipy.special.lambertw', 'numpy.core._string_helpers', 'Bio.GenBank.utils', 'graph_peak_caller.peakfasta', 'tempfile', 'numpy.lib.arraysetops', 'scipy', 'string', 'scipy.optimize._slsqp', 'matplotlib', 'unittest.main', 'multiprocessing', 'distutils.version', '_opcode', '_pickle', 'scipy.optimize._trustregion_dogleg', 'scipy.stats.kde', 'numpy.lib.polynomial', 'Bio.Seq', 'genericpath', 'scipy.linalg._matfuncs_sqrtm', 'pyvg.sequences', 'numpy.testing._private', 'async_generator._version', 'scipy.sparse.linalg.dsolve', 'scipy.optimize._trustregion_ncg', 'time', 'graph_peak_caller.sample', 'scipy._lib._uarray', 'async_generator._impl', 'sys', 'threading', 'hashlib', 'numpy.lib._iotools', 'scipy._lib._ccallback_c', 'scipy.integrate.vode', 'scipy.optimize._trustregion_constr.minimize_trustregion_constr', 'offsetbasedgraph.interval', 'scipy.optimize._constraints', 'graph_peak_caller.shiftestimation.shiftestimation', 'bisect', 'asyncio.base_subprocess', 'google.protobuf.text_format', 'zipimport', 'scipy.integrate._ivp.bdf', 'scipy.optimize._lsap', 'concurrent', 'scipy.sparse.linalg.matfuncs', 'scipy.linalg._flinalg', 'google.protobuf.internal.type_checkers', 'email._policybase', 'textwrap', 'numpy.core', 'scipy.linalg._decomp_ldl', 'urllib', 'keyword', 'locale', 'asyncio.constants', 'scipy.special._comb', 'scipy.linalg.decomp_lu', 'importlib', 'io', 'sqlite3.dbapi2', 'graph_peak_caller.sparsediffs', 'matplotlib.cbook', 'scipy.special._basic', 'scipy.misc.doccer', 'linecache', 'scipy.stats._stats', 'queue', 'asyncio.transports', 'subprocess', 'offsetbasedgraph.sequencegraphv2', 'gc', 'scipy.sparse.linalg.isolve.lsmr', 'random', 'copy', 'Bio.Align', '_frozen_importlib_external', 'sre_constants', 'distutils', 'scipy.constants.codata', 'scipy.special._ufuncs', 'matplotlib.colors', 'numpy.core._multiarray_tests', 'platform', 'graph_peak_caller.haplotyping', 'numpy.random._philox', '__mp_main__', 'scipy.special._spherical_bessel', 'scipy.ndimage', 'graph_peak_caller.postprocess.segmentanalyzer', 'pyvg.vg_pb2', 'numpy.random.mtrand', 'reprlib', 'glob', 'numpy.lib.twodim_base', 'scipy.linalg.cython_lapack', 'Bio.SeqIO.AbiIO', '_sitebuiltins', 'scipy.ndimage.interpolation', 'google.protobuf.symbol_database', 'pathlib', 'scipy.stats._constants', 'xml.sax', '_imp', 'scipy.sparse.lil', 'scipy.linalg._flapack', 'ast', 'scipy.optimize._shgo_lib.triangulation', 'graph_peak_caller.control.linearmap', 'Bio.Sequencing.Ace', 'scipy.linalg.decomp', 'scipy._lib._uarray._uarray', 'google.protobuf.internal.api_implementation', 'numpy.ma.core', 'copyreg', 'marshal', 'scipy.stats._continuous_distns', 'numpy.linalg', 'importlib.util', 'pyfaidx', 'scipy.interpolate._pade', 'graph_peak_caller.analysis.peakscomparer', 'lzma', 'decimal', 'multiprocessing.util', 'graph_peak_caller.summits', 'offsetbasedgraph.directedinterval', 'unittest', 'numpy.testing', 'scipy.stats._hypotests', 'graph_peak_caller.control.linearpileup', 'asyncio.queues', 'scipy.sparse.csgraph._min_spanning_tree', 'scipy.stats.mstats_extras', 'email.quoprimime', 'scipy.stats.distributions', 'math', 'scipy.fft._realtransforms', 'collections', 'xml.sax.xmlreader', 'scipy.integrate.odepack', 'scipy.sparse._sparsetools', 'Bio.SeqIO.FastaIO', 'scipy.sparse.linalg.dsolve.linsolve', 'numpy.core.defchararray', 'Bio.Alphabet', 'scipy.fft._pocketfft.basic', 'scipy.linalg.decomp_svd', 'scipy.integrate._ivp.base', 'scipy.ndimage._nd_image', 'scipy.sparse.linalg.eigen.arpack.arpack', 'scipy.stats._stats_mstats_common', 'scipy.linalg.blas', 'bz2', 'typing', 'pyexpat.model', 'numpy.lib._datasource', 'scipy.stats.morestats', 'matplotlib.fontconfig_pattern', 'scipy.linalg.special_matrices', 'scipy.optimize._minpack', 'numpy.core.numeric', 'scipy.interpolate.ndgriddata', 'scipy.linalg.decomp_qr', 'numpy.core.machar', 'datetime', 'numpy.lib.financial', 'scipy.linalg._decomp_update', 'scipy.interpolate._ppoly', 'scipy.special', 'scipy.linalg.matfuncs', 'numpy.core._exceptions', 'asyncio', 'xml.etree', 'graph_peak_caller.postprocess.reference_based_max_path', 'pickle', 'encodings', 'numbers', 'scipy.sparse.dok', 'importlib._bootstrap_external', 'numpy.__config__', 'scipy.sparse.linalg.dsolve._superlu', 'numpy.matrixlib.defmatrix', 'graph_peak_caller.analysis.analysis_interface', 'scipy.stats._rvs_sampling', 'dateutil._version', 'scipy.optimize._root', 'numpy.random._pcg64', '_collections', 'scipy.interpolate.interpolate', 'scipy.sparse.data', 'scipy.stats', 'unittest.signals', 'scipy.linalg._decomp_qz', 'numpy.polynomial.polynomial', '_thread', 'unittest.result', 'scipy.optimize._lsq', 'numpy.fft._pocketfft_internal', 'scipy.stats._tukeylambda_stats', 'scipy.integrate._ivp.rk', 'numpy.polynomial._polybase', 'scipy.sparse.linalg.dsolve._add_newdocs', 'scipy.spatial.kdtree', 'scipy.misc', 'scipy.linalg._expm_frechet', 'scipy.optimize._basinhopping', 'graph_peak_caller.postprocess.maxpaths', 'google.protobuf.message', 'graph_peak_caller.control.controlgenerator', 'scipy.optimize._shgo_lib', 'scipy.sparse.linalg._onenormest', 'multiprocessing.reduction', 'scipy._lib._ccallback', 'scipy.optimize._trustregion_constr.equality_constrained_sqp', 'asyncio.unix_events', 'abc', 'numpy.lib.type_check', 'numpy.core.multiarray', 'google.protobuf.internal.message_listener', 'multiprocessing.connection', 'Bio._utils', 'six', 'unittest.case', 'numpy.polynomial.legendre', '_sysconfigdata', 'scipy.spatial._distance_wrap', 'xml', 'scipy.sparse.compressed', 'google.protobuf.internal.extension_dict', 'os.path', 'scipy.interpolate.dfitpack', 'scipy.spatial', 'graph_peak_caller.callpeaks_interface', '_decimal', 'binascii', '_sqlite3', 'stream.stream', 'numpy.compat.py3k', 'scipy.ndimage.filters', 'dateutil', 'multiprocessing.process', 'email.header', '_ssl', 'scipy.sparse._index', 'asyncio.compat', 'scipy.integrate', '__main__', 'scipy.optimize._dual_annealing', 'scipy.optimize._bglu_dense', 'numpy.lib.mixins', 'numpy.polynomial', '_struct', 'numpy._globals', 'Bio.Data.IUPACData', 'operator', 'graph_peak_caller.analysis.venn_diagrams', 'scipy.__config__', 'scipy.special.sf_error']
DEBUG:matplotlib:CACHEDIR=/home/fieldp/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/fieldp/.cache/matplotlib/fontlist-v300.json
DEBUG:matplotlib.pyplot:Loaded backend agg version unknown.
2023-02-09 11:49:16,960, INFO: Sample files: ['alignments.json']
2023-02-09 11:49:16,960, INFO: Using graphs: ['ch19.nobg']
2023-02-09 11:49:16,960, INFO: Will use sequence graphs. ['ch19.nobg.sequences']
2023-02-09 11:49:16,960, INFO: Using graphs from data directory ./
2023-02-09 11:49:16,960, INFO: Will use [''] as extra experiments names for each run, based on graph file names.If only running on single graph, this should be empty.
2023-02-09 11:49:16,960, WARNING: Did not find linear map for  for graph ch19.nobg. Will create.
2023-02-09 11:49:16,960, WARNING: Did not find linear map for  for graph ch19.nobg. Will create.
2023-02-09 11:49:17,422, INFO: Getting topologically sorted nodes
2023-02-09 11:49:17,422, INFO: 0 nodes processed
Traceback (most recent call last):
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/bin/graph_peak_caller", line 8, in <module>
    sys.exit(main())
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/graph_peak_caller/command_line_interface.py", line 36, in main
    run_argument_parser(sys.argv[1:])
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/graph_peak_caller/command_line_interface.py", line 673, in run_argument_parser
    args.func(args)
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/graph_peak_caller/callpeaks_interface.py", line 182, in run_callpeaks2
    create_linear_map(graph, linear_map_name)
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/graph_peak_caller/util.py", line 6, in create_linear_map
    linear_map = LinearMap.from_graph(ob_graph)
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/graph_peak_caller/control/linearmap.py", line 104, in from_graph
    node_ids = list(graph.get_topological_sorted_node_ids())
  File "/home/fieldp/miniconda3/envs/graph_peak_caller/lib/python3.5/site-packages/offsetbasedgraph/graph.py", line 539, in get_topological_sorted_node_ids
    assert not unfinished, unfinished
AssertionError: {190627: 1}
```

Please let me know if any additional information would be helpful to determine what is going wrong.

**Comment by cgroza** [comment]
Graphs from PGGB contain cycles. This part of GraphPeakCaller is trying to topologically sort the graph, which is not defined for graphs with cycles. Therefore, GraphPeakCaller is not compatible with graphs that contain cycles.
