### ISSUE TITLE
IndexError when running callpeaks

### ISSUE THREAD

**Issue by heng-le** [uio-bmi/graph_peak_caller#16]
Hello! I got the following error when I was trying to run the callpeaks command: `graph_peak_caller callpeaks -g ENC001_graph.nobg -s enc001_exp_single_rep9_mapped_filtered.json --control transverse_colon_enc001_control_single_rep7_mapped_filtered.json`

Error message:
`2024-12-27 09:25:02,958, INFO: Creating background from control reads
Traceback (most recent call last):
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/bin/graph_peak_caller", line 8, in <module>
    sys.exit(main())
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/command_line_interface.py", line 37, in main
    run_argument_parser(sys.argv[1:])
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/command_line_interface.py", line 700, in run_argument_parser
    args.func(args)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/callpeaks_interface.py", line 251, in run_callpeaks2
    caller.run()
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/multiplegraphscallpeaks.py", line 71, in run
    self.run_to_p_values()
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/multiplegraphscallpeaks.py", line 118, in run_to_p_values
    caller.run_to_p_values(sample, control)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/callpeaks.py", line 122, in run_to_p_values
    self.run_pre_callpeaks(input_intervals, control_intervals)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/callpeaks.py", line 62, in run_pre_callpeaks
    control_pileup = background_func(self.graph, control_reads,
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/control/__init__.py", line 20, in get_background_track_from_control
    return get_background_track(graph, intervals, config,
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/control/__init__.py", line 13, in get_background_track
    return sc.create(intervals)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/control/controlgenerator.py", line 22, in create
    mapped_reads = self._linear_map.map_interval_collection(reads)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/control/linearmap.py", line 55, in map_interval_collection
    start, end = self.map_graph_interval(interval)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/control/linearmap.py", line 61, in map_graph_interval
    start_pos = self.graph_position_to_linear(interval.start_position)
  File "/gpfs/gibbs/pi/gerstein/hc865/cvenv/lib/python3.10/site-packages/graph_peak_caller/control/linearmap.py", line 67, in graph_position_to_linear
    node_start = self._node_starts[node_id]
IndexError: index 102582752 is out of bounds for axis 0 with size 8938731`

Would anyone know what the problem may be? The vg file was created as such: `vg construct -r hs1.fa -v pav_ENC001_fix2.vcf.gz -a > ENC001_graph.vg`
and mapped using `vg map -f ENCFF762UTU.fastq.gz -x ENC001_graph.xg -g ENC001_graph.gcsa > transverse_colon_enc001_exp_single_rep1_mapped.gam  `

**Comment by heng-le** [comment]
For anyone facing this issue, downgrading to vg version 1.20.0 worked
